
#http://127.0.0.1:8000/


site_name: CHESS ID4B QM2
site_url: https://example.com/
repo_url: https://github.com/suchismitasarker/CHESS-ID4B-QM2/blob/main/README.md
copyright: © Copyright 2024, CHESS ID4B Beamline
generator: false

extra:
  generator: false

nav:
    - Home: 
        - Welcome : 'index.md'
        - 'User Guide':
            - Introduction: 'introduction.md'
            - Beamline information : 'beamline_parameters.md'
            - ID4B-SPEC commands: 'SPEC_commands.md'
            - 'Sample information':
                - Sample environment : sample_env.md
                - Sample mount : sample.md
                - 'Sample alignment':
                    - HDRM : sample_alignment_HDRM.md
                    - REXS : sample_alignment_REXS.md
                - Temperature switch : temp.md
                - Gas flow control : gas_flow.md
            - 'Data Analysis':
                - Data processing : ID4B_Codes.md
                - General node : ID4B_Codes_general_nodes.md
                - NxRefine General Node : nxrefine_General_Node.md
                - NxRefine : nxrefine.md
                - 'Data visualization': 
                    - NeXpy : nexpy.md 
                    - pyMCA : pymca.md
            - 'Beamline equipments' :
                - Cameras : PTZ_camera.md
                - Diffractometer : diffractometer.md
                - Cryocooler : cryocooler.md
                - Detector : detector_information.md
                - Publication : publications.md
        - Troubleshooting :
            - IC1 signal issues : IC1_signal.md
            - Beam dump : beam_dump.md
        - Admin Documentation :
            - Beamline setup : beamline_setup.md
            - Cryostat : Cryostat.md
            - Energy change : energy_change.md
            - SPEC macro : SPEC_macros.md  
        - Frequently Asked Questions (FAQ) : 
            - Before coming to the beamline : 'information.md'
            - Beamline Frequently Asked Questions: 'FAQ.md'
        
        - About:
            - About: about.md
            - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
    
    

theme: 
    name: readthedocs
    docs_dir: 'mkdocs-material/material'
    theme_dir: material/material
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    features:
        - navigation.indexes

    analytics: 
        gtag: G-ABC123

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - codehilite:
      guess_lang: false
      use_pygments: true

:root > * { --md-code-hl-string-color: #0FF1CE; }


extra:
  generator: false

plugins:
    - mkdocs-video



