
#http://127.0.0.1:8000/


site_name: CHESS ID4B QM2
site_url: https://example.com/
repo_url: https://github.com/suchismitasarker/CHESS-ID4B-QM2/blob/main/README.md
copyright: © Copyright 2025, CHESS ID4B Beamline
#generator: false

extra:
  generator: false

nav:
    - Home: 
        - Welcome : 'index.md'
        - 'Beamline information' :
            - Introduction: 'introduction.md'
            - Beamline Publications : publications.md
            - Beamline USER Guide : 'beamline_parameters.md'  
            - 'Sample information':
                - Sample environment : sample_env.md
                - Sample mount : sample.md
                - ID4B-SPEC commands: 'SPEC_commands.md'
                - Beamline basics: beamline_basics.md
                - 'Sample alignment':
                    - HDRM : sample_alignment_HDRM.md
                    - REXS : sample_alignment_REXS.md
                - Temperature switch : temp.md
                - Gas flow control : gas_flow.md
            - 'Data Analysis':
                - Data processing : ID4B_Codes.md
                - General node : ID4B_Codes_general_nodes.md
                - NxRefine General Node : nxrefine_General_Node.md
                - NxRefine : nxrefine.md
                - Detailed Data Analyis : detailed_dataanalysis.md
                - 'Data visualization': 
                    - NeXpy : nexpy.md 
                    - pyMCA : pymca.md
            - 'Beamline equipments' :
                - Cameras : PTZ_camera.md
                - Diffractometer : diffractometer.md
                - Cryocooler : cryocooler.md
                - Detector : detector_information.md   
        - 'Things to check during beamtime' :
            - Note : note.md
        - Troubleshooting :
            - IC1 signal issues : IC1_signal.md
            - Control C Questions : controlC_question.md
            - Beam dump : beam_dump.md
            - Missing SPEC : lost_fourc.md
            - Camera image stuck : camera_image_stuck.md 
            - NexPy crushed : nexpy_crushed.md 
            - Lower diode signal : lower_diode_signal.md 
            - Cryostream sudden failure: cryo_fail.md
            - Computer Issues: comp_issues.md
        - Admin Documentation :
            - Beamline setup : beamline_setup.md
            - Cryostat : Cryostat.md
            - Energy change : energy_change.md
            - SPEC macro : SPEC_macros.md  
        - Frequently Asked Questions (FAQ) : 
            - Before coming to the beamline : 'information.md'
            - Beamline Frequently Asked Questions: 'FAQ.md'
        
        - About:
            - About: about.md
            - License: 'license.md'
            
        
    
    

theme: 
    name: readthedocs
    docs_dir: 'mkdocs-material/material'
    theme_dir: material/material
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    features:
        - navigation.indexes

    analytics: 
        gtag: G-ABC123

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - codehilite:
      guess_lang: false
      use_pygments: true


plugins:
    - mkdocs-video

#extra_css:
#    - css/extra.css



